<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ballcom.ProductCatalog.Domain\Ballcom.ProductCatalog.Domain.csproj" />
    <ProjectReference Include="..\contracts\ProductCreatedEvent\Events.csproj" />
    <ProjectReference Include="..\Ballcom.ProductCatalog.Domain\Ballcom.ProductCatalog.Domain.csproj" />
    <ProjectReference Include="..\contracts\ProductCreatedEvent\Events.csproj" />
  </ItemGroup>

</Project>
