<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ballcom.Payment.Application\Ballcom.Payment.Application.csproj" />
		<ProjectReference Include="..\Ballcom.Payment.Domain\Ballcom.Payment.Domain.csproj" />
		<ProjectReference Include="..\contracts\ProductCreatedEvent\Events.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="MassTransit" Version="8.3.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	    <PrivateAssets>all</PrivateAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
