<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Ballcom.MigrationService-0b6f2df5-1b61-4f42-8cb8-fb408e9d387f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Aspire\Aspire.ServiceDefaults\Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Ballcom.CustomerService.Infrastructure\Ballcom.CustomerService.Infrastructure.csproj" />
    <ProjectReference Include="..\Ballcom.Identity.Infrastructure\Ballcom.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Ballcom.Order.Infrastructure\Ballcom.Order.Infrastructure.csproj" />
    <ProjectReference Include="..\Ballcom.ProductCatalog.Infrastructure\Ballcom.ProductCatalog.Infrastructure.csproj" />
  </ItemGroup>
</Project>
