<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Ballcom.ProductCatalog.Infrastructure\Ballcom.ProductCatalog.Infrastructure.csproj" />
    <ProjectReference Include="..\src\contracts\ProductCreatedEvent\Events.csproj" />
  </ItemGroup>

</Project>
