<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ballcom.Shipment.Domain\Ballcom.Shipment.Domain.csproj" />
    <ProjectReference Include="..\contracts\ProductCreatedEvent\Events.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.0" />
  </ItemGroup>

</Project>
