<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ballcom.Payment.Domain\Ballcom.Payment.Domain.csproj" />
		<ProjectReference Include="..\contracts\ProductCreatedEvent\Events.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="MassTransit" Version="8.3.0" />
	</ItemGroup>

</Project>
